# Where to find documentation
docs_dir: doc

# Link to Github on every page
repo_url: https://github.com/openfoodfacts/robotoff
edit_uri: blob/main/doc/

site_name: Robotoff
site_dir: gh_pages

theme:
  name: material
  features:
    - content.action.edit
  logo: https://static.openfoodfacts.org/images/logos/off-logo-horizontal-light.svg
  favicon: https://static.openfoodfacts.org/images/logos/off-logo-favicon-light.png
markdown_extensions:
  - footnotes
  - mdx_truly_sane_lists
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - awesome-pages
  - search
